version: "3.9"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: image
      POSTGRES_PASSWORD: image
      POSTGRES_DB: image
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
